version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: plasmic
      POSTGRES_USER: plasmic
      POSTGRES_PASSWORD: plasmic123
    volumes:
      - plasmic_db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plasmic"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  plasmic_db_data: