services:
  app:
    build:
      context: .
      dockerfile: production.Dockerfile
    restart: always
    environment:
      - DATABASE_URI=postgresql://wab:SEKRET@142.44.136.233:5432/plasmic-db
      - WAB_DBHOST=142.44.136.233
      - WAB_DBUSER=wab
      - WAB_DBPASSWORD=SEKRET
      - WAB_DBNAME=plasmic-db
      - NODE_ENV=production
      - PUBLIC_URL=http://localhost:3003
      - SESSION_SECRET=plasmicapp_session_secret_key
      - PLASMIC_DEPLOYMENT_ENV=production
    ports:
      - "3003-3005:3003-3005"
    command: sh -c "sleep 30 && cd /app/platform/wab && yarn typeorm migration:run && yarn backend"